# Generated by Django 3.2.8 on 2021-10-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='time',
        ),
    ]
